# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""Resolve direct-descriptor protobuf model references."""

from __future__ import annotations

from collections.abc import Mapping

from score.parsers.protobuf_parser.common import (
    ProtoResolverIssue,
    ReferenceTargetKind,
    SourceSpan,
    UnresolvedReference,
)
from score.ecu_model.data_types.array import ArrayDataType
from score.ecu_model.data_types.common import DataTypeBase
from score.ecu_model.data_types.map import MapDataType


class ProtoResolverError(ValueError):
    """Raised when resolver phase fails."""


def _unresolved_target_issue(
    unresolved: UnresolvedReference,
    *,
    code: str,
    message: str,
) -> ProtoResolverIssue:
    return ProtoResolverIssue(
        phase="resolver",
        code=code,
        message=message,
        span=SourceSpan(file_path=unresolved.file_path, line=1),
    )


def _assign_resolved_reference(
    unresolved: UnresolvedReference,
    resolved_definition: DataTypeBase,
) -> ProtoResolverIssue | None:
    """Locate an unresolved reference target and replace it with its resolved definition."""
    target = unresolved.target

    if target.kind == ReferenceTargetKind.FIELD_DATA_TYPE:
        target.field.data_type = resolved_definition
        return None

    if target.kind == ReferenceTargetKind.ARRAY_ELEMENT_TYPE:
        if not isinstance(target.field.data_type, ArrayDataType):
            return _unresolved_target_issue(
                unresolved,
                code="unresolved_reference_target_invalid",
                message=(
                    f"Unresolved array field '{target.field.name.as_str}' in "
                    f"'{target.owner_definition_key}' is not an array"
                ),
            )
        target.field.data_type.data_type = resolved_definition
        return None

    if target.kind in (ReferenceTargetKind.MAP_KEY_TYPE, ReferenceTargetKind.MAP_VALUE_TYPE):
        if not isinstance(target.field.data_type, MapDataType):
            return _unresolved_target_issue(
                unresolved,
                code="unresolved_reference_target_invalid",
                message=(
                    f"Unresolved map field '{target.field.name.as_str}' in '{target.owner_definition_key}' is not a map"
                ),
            )
        if target.kind == ReferenceTargetKind.MAP_KEY_TYPE:
            target.field.data_type.key_type = resolved_definition
        else:
            target.field.data_type.value_type = resolved_definition
        return None

    return _unresolved_target_issue(
        unresolved,
        code="unresolved_reference_target_invalid",
        message=f"Unresolved reference target '{target.owner_definition_key}' has an unknown kind",
    )


def resolve_references(
    unresolved_references: list[UnresolvedReference],
    definitions_by_key: Mapping[str, DataTypeBase],
) -> list[ProtoResolverIssue]:
    """Resolve references from a complete descriptor set validated by protoc.

    The context must originate from a ``FileDescriptorSet`` generated by
    successful protoc compilation. Import availability and symbol visibility are
    validated by protoc before this phase.
    """
    resolver_issues: list[ProtoResolverIssue] = []

    for unresolved in unresolved_references:
        if not unresolved.protobuf_type_name:
            continue
        definition_key = unresolved.protobuf_type_name.lstrip(".")
        resolved_definition = definitions_by_key.get(definition_key)
        if resolved_definition is None:
            resolver_issues.append(
                ProtoResolverIssue(
                    phase="resolver",
                    code="unresolved_type",
                    message=(f"Cannot resolve type '{unresolved.protobuf_type_name}' in '{unresolved.file_path}'"),
                    span=SourceSpan(file_path=unresolved.file_path, line=1),
                )
            )
            continue

        assignment_issue = _assign_resolved_reference(
            unresolved,
            resolved_definition,
        )
        if assignment_issue is not None:
            resolver_issues.append(assignment_issue)

    return resolver_issues
