# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""Validate Bazel-owned public Protobuf import visibility semantics."""

from __future__ import annotations

import os
from pathlib import Path
import pickle
import unittest


class ProtobufImportVisibilityIntegrationTest(unittest.TestCase):
    """Test public transitive import behavior through Bazel."""

    def test_given_public_import_chain_when_compiling_then_transitive_symbol_is_resolved(self):
        registry = load_public_import_registry()["datatypes"]

        self.assertIn("demo.a.AMessage", registry)
        self.assertIn("demo.c.CMessage", registry)


def load_public_import_registry():
    """Load the registry generated by the Bazel descriptor pipeline."""
    runfiles_root = Path(os.environ["RUNFILES_DIR"])
    output_path = next(runfiles_root.rglob("public_import_model.pickle"))
    return pickle.loads(output_path.read_bytes())


if __name__ == "__main__":
    unittest.main()
